# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gil-demo-app' do
  # Comment the next line if you don't want to use dynamic frameworks
use_frameworks!
pod 'ACPTarget', '~> 2.1'
pod 'ACPAnalytics', '~> 2.0'
pod 'ACPCore', '~> 2.0'
pod 'ACPUserProfile', '~> 2.0'
  # Pods for gil-demo-app

end
